[{* Including widget for Paymorrow JavaScript/CSS initiation *}]
[{if $paymentmethod->isPaymorrowActiveAndMapped()}]
    [{oxid_include_widget cl="oxpspaymorrowinit" noscript=1 nocookie=1}]
    [{if $paymentmethod->getPaymorrowPaymentType() == 'pm_invoice'}]
        [{include file="paymorrow_payment_invoice.tpl" pmPaymentId=$paymentmethod->getId()}]
    [{elseif $paymentmethod->getPaymorrowPaymentType() == 'pm_sdd'}]
        [{include file="paymorrow_payment_direct_debit.tpl" pmPaymentId=$paymentmethod->getId()}]
    [{/if}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]